# Generated by Django 5.0.7 on 2025-09-26 15:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'third_party'}, on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractEnrolledStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Enrolled Student',
                'verbose_name_plural': 'Contract Enrolled Students',
                'unique_together': {('contract', 'student')},
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='enrolled_students',
            field=models.ManyToManyField(related_name='contracts_enrolled_in', through='contracts.ContractEnrolledStudent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ContractLearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.learningpath')),
            ],
            options={
                'verbose_name': 'Contract Learning Path',
                'verbose_name_plural': 'Contract Learning Paths',
                'unique_together': {('contract', 'learning_path')},
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='learning_paths',
            field=models.ManyToManyField(related_name='contracts', through='contracts.ContractLearningPath', to='learning.learningpath'),
        ),
    ]
